### ISSUE TITLE
Easier way to Exit & Quit to default/Customize mutiple units [Feature Request]

### ISSUE THREAD

**Issue by big610** [ad2017gd/RainbowTaskbar#4] opened 2021-10-16 20:08 UTC
When you Right Click Exit, Task Bar remains transparent to the Windows blue, Restart to get the Task Bar back to default Black. Can a option be added to return to default?

Those with 2 or more units, a easy menu way to customize, so you have a different color scheme for each unit, making it easier to tell which unit immediately is which. Ideal for multiple units, to set a color, scheme, to label them.

**Comment by ad2017gd** [comment] 2021-10-16 23:22
Hello! I am aware of the transparent taskbar bug, which I might fix soon, even though it seems to get kind of fixed when i interact with the taskbar buttons. Could you elaborate on the second paragraph though? Thank you!

**Comment by ad2017gd** [comment] 2021-10-16 23:47
1ae1e4c83739cd89ba050f879cc0ba20d03951a3
1/2 -> Transparency bug fixed in latest config

**Comment by ad2017gd** [comment] 2021-10-16 23:48
> 
> 
> When fixing the transparent bug, you need the full function quit. I can only quit with a Restart.
> 
> 2 or more computers: If an individual has two computers, whether side by side or switching with a switch. A place with multiple computers & monitors; Educational Work Lab, Library, Work Environment. Ability for the User or Administrator to give a computer a custom color or scheme to distinguish between each other. If using a a switch with one monitor, the ability to see the difference, choosing a custom rainbow or color. For multiple monitors, Admin, can single out a particular unit or person, giving it a custom rainbow or color. Then can easily re-set back to Default setting. This could be used to flag a unit or person.

I still don't quite understand. Are you suggesting a multiple config option for different functionality on each display?

**Comment by big610** [comment] 2021-10-16 23:54
The ability to choose a custom coloring or rainbow scheme.
Unit 1 Example: Red-Orange rainbow scheme
Unit 2 Example: Blue-Purple rainbow scheme
or more easier for RGB coding:
Unit 1 Example: Red
Unit 2 Example: Green

**Comment by ad2017gd** [comment] 2021-10-16 23:57
Let me reiterate. Are you suggesting the ability to have different configs on each monitor, or just shortcuts for other configs as a whole?

**Comment by big610** [comment] 2021-10-17 00:01
Yes the ability to set the app to a custom coloring rainbow scheme on one computer = 1 computer unit.

Then a 2nd computer you could choose a different colored rainbow scheme.

**Comment by ad2017gd** [comment] 2021-10-17 00:04
Anyway, I will currently release a new build for the first fix, as this feature would mean completely changing my current config system, which is not only gonna take a while, but I'm also quite burned out from working so much on this recently. Thanks for the suggestion anyway!

**Comment by ad2017gd** [comment] 2021-10-17 00:25
Can't your intended behavior just be done using my config examples, or just creating or own? Or is it that the actual idea is lost in translation (I'm having a hard time really understanding what you mean)

**Comment by big610** [comment] 2021-10-17 00:36
Using your config examples, could be very well possible. I see an issue getting it to Apply, and need a Reset to Default to test easier. Your directions under Editor could use more refinement.

**Comment by ad2017gd** [comment] 2021-10-17 00:40
Alright, I will try to think about a few more examples, bundle them in, and maybe explain the editor a bit better. I don't think a reset button is needed, as exiting from the taskbar icon will reset it to the default taskbar.
The apply issue usually only applies to static configs, such as image-only configs, or ones with infinite wait. This can also be easily fixed.

Thank you for the feedback!

**Closed by ad2017gd** 2021-10-17 00:40 UTC
Labels: bug, enhancement

**Comment by ad2017gd** [comment] 2021-10-17 12:50
Fixed in latest config c817c4aabf9b060c94ad47537c4b52f08ae11597 (v1.3.3)
