### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by JusEzio** [ad2017gd/RainbowTaskbar#33] opened 2023-04-01 18:26 UTC
When trying to make the taskbar transparent it make the icons transparent too.

**Comment by ad2017gd** [comment] 2023-04-02 08:33
im assuming you are talking about the transparency instruction targeting the taskbar
that is actually intended behavior, you're supposed to use the transparency style option set to transparent

do note that it is currently broken in latest win 11 (#32, #31, ...)

**Comment by ad2017gd** [comment] 2023-04-02 08:33
![image](https://user-images.githubusercontent.com/39013925/229341743-c9b9f538-8d01-4119-b98a-33e08acda621.png)

**Comment by JusEzio** [comment] 2023-04-04 00:00
Yea, icons on taskbar disappear too and you cant click on that and yes I'm on win 11 so basically is a error on app.

**Comment by ad2017gd** [comment] 2023-08-17 16:03
I think this is fixed in 2.3.1 (e918aa5) ??

**Closed by ad2017gd** 2023-08-17 16:03 UTC
